version: "2"
linters:
  default: all
  disable:
    - depguard
    - dupl
    - forcetypeassert
    - gochecknoglobals
    - godox
    - ireturn
    - mnd
    - nakedret
    - nlreturn
    - paralleltest
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - testpackage
    - tparallel
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 100
    exhaustruct:
      exclude:
        - http.Cookie
        - http.Server
        - .+Error$
        - http.Client
        - cors.Cors
        - cors.Options
        - go2node.NodeMessage
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - trace
        - logr
    revive:
      rules:
        - name: unexported-return
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1003
    varnamelen:
      ignore-names:
        - err
        - id
        - t
      ignore-decls:
        - r *http.Request
        - rw http.ResponseWriter
    wrapcheck:
      ignore-sigs:
        - (context.Context).Err()
        - fmt.Errorf(
      ignore-sig-regexps:
        - \.New.*Error\(
      ignore-package-globs:
        - encoding/*
        - time
        - io/fs
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
          - forcetypeassert
          - funlen
          - gochecknoglobals
          - lll
          - nosnakecase
          - varnamelen
          - wrapcheck
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
